apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: multi-apps-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.alb.ingressClass }}
    alb.ingress.kubernetes.io/scheme: {{ .Values.alb.scheme }}
    alb.ingress.kubernetes.io/target-type: {{ .Values.alb.targetType }}
    alb.ingress.kubernetes.io/subnets: {{ join "," .Values.alb.subnets }}
spec:
  rules:
    - http:
        paths:
{{- range .Values.apps }}
          - path: {{ .path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .name }}-service
                port:
                  number: 80
{{- end }}
